/*
#SQL#
#CREATE DATABASE 
CREATE DATABASE myDB;
#ALTER DATABASE - MAKE READ ONLY - CANNOT MAKE ALTERATIONS, VIEW ONLY.
ALTER DATABASE myDB READ ONLY = 1;
DROP DATABASE myDB;
#RETURN TO EDIT MODE - READ ONLY = 0
ALTER DATABASE myDB READ ONLY = 0;
#DROP DATABASE
DROP DATABASE myDB;
*/

/*#TABLE CREATION AND OPERATIONS
CREATE TABLE EMPLOYEES(
 employee_id INT,
 first_name VARCHAR(50),
 last_name VARCHAR(50), 
 hourly_pay DECIMAL(5,2),
 hire_date DATE
 );
 */
#SELECT * FROM EMPLOYEES;
#RENAME TABLE EMPLOYEES TO WORKERS;
#RENAME TABLE WORKERS TO EMPLOYEES;
#ALTER TABLE EMPLOYEES ADD phone_number VARCHAR(15);
#SELECT * FROM EMPLOYEES;
#ALTER TABLE EMPLOYEES RENAME COLUMN PHONE_NUMBER TO EMAIL;
#SELECT * FROM EMPLOYEES;
#ALTER TABLE EMPLOYEES MODIFY COLUMN EMAIL VARCHAR(100);
#SELECT * FROM EMPLOYEES
#ALTER TABLE EMPLOYEES MODIFY EMAIL VARCHAR(100) AFTER LAST_NAME;
#SELECT * FROM EMPLOYEES
#ALTER TABLE EMPLOYEES MODIFY EMAIL VARCHAR(100) FIRST;
#SELECT * FROM EMPLOYEES
#ALTER TABLE EMPLOYEES DROP COLUMN EMAIL;
#SELECT * FROM EMPLOYEES


#INSERT ROWS
/*INSERT INTO EMPLOYEES
VALUES(1,"ALEX","TITTO",25.23,"2026-01-02"),(2,"ALEX","KURIAKOSE",30.23,"2025-01-08"),(3,"JAYAKRISHNAN","KV",28.75,"2026-05-27"),(4,"RON","ROY",26.15,"2025-08-02");
SELECT * FROM EMPLOYEES
*/

#INSERT ROW WITH INSUFFICIENT DATA
/*INSERT INTO EMPLOYEES(EMPLOYEE_ID,FIRST_NAME,LAST_NAME) VALUES(5,"EJO","BENNY");
SELECT * FROM EMPLOYEES;
*/


#select first_name, last_name from employees;

#select * from employees where first_name = "jayakrishnan";

#select * from employees where hourly_pay > 27;

#select * from employees where hire_date is null;
#select * from employees;


#SET SQL_SAFE_UPDATES = 0;
/*UPDATE AND DELETE OPERATIONS*/

/*#UPDATE EMPLOYEES SET HIRE_DATE = "2025-02-27" WHERE EMPLOYEE_ID = 5;
#UPDATE EMPLOYEES SET EMPLOYEE_ID = 1 WHERE EMPLOYEE_ID = 4;
#UPDATE EMPLOYEES SET EMPLOYEE_ID = 2 WHERE EMPLOYEE_ID = 5;
#UPDATE EMPLOYEES SET EMPLOYEE_ID = 4 WHERE LAST_NAME = "TITTO";
UPDATE EMPLOYEES SET EMPLOYEE_ID = 5 WHERE LAST_NAME = "KURIAKOSE";

select * from employees;
*/
 
#INSERT INTO EMPLOYEES VALUES(6,"BASIL","BABY",30,"2026-09-16");
#UPDATE EMPLOYEES SET HOURLY_PAY = NULL WHERE EMPLOYEE_ID = 6;
#DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 6;

select * from employees;